import { Hono } from "hono";
import { db } from "../database";
import * as schema from "../database/schema";

// Real/original products — shown in main marketplace feed
const originalProducts = [
  {
    title: "Apple AirPods Pro (2nd Gen)",
    description: "Brand new, sealed box. Active Noise Cancellation, Transparency mode, Adaptive Audio. MagSafe charging case included.",
    originalPrice: 24900,
    reloopPrice: 24900,
    imageUrl: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Apple",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 20,
    co2SavedKg: 1.0,
    status: "active",
    views: 342,
    isReturnedItem: false,
  },
  {
    title: "Sony WH-1000XM5 Headphones",
    description: "Industry-leading noise cancellation. 30h battery, multipoint connection. Brand new in box.",
    originalPrice: 29990,
    reloopPrice: 29990,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Sony",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 20,
    co2SavedKg: 1.2,
    status: "active",
    views: 198,
    isReturnedItem: false,
  },
  {
    title: "Nike Air Max 270",
    description: "Nike's largest Air unit yet. Lightweight, breathable mesh upper. Available in multiple sizes.",
    originalPrice: 10995,
    reloopPrice: 10995,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    category: "footwear",
    brand: "Nike",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 15,
    co2SavedKg: 0.8,
    status: "active",
    views: 167,
    isReturnedItem: false,
  },
  {
    title: "Samsung Galaxy Tab S9",
    description: "11-inch Dynamic AMOLED display, Snapdragon 8 Gen 2, IP68, S Pen included.",
    originalPrice: 72999,
    reloopPrice: 72999,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4cec9d125?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Samsung",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 25,
    co2SavedKg: 2.0,
    status: "active",
    views: 413,
    isReturnedItem: false,
  },
  {
    title: "Levi's 512 Slim Taper Jeans",
    description: "Classic slim taper fit. Flexible waistband. Available in multiple washes and sizes.",
    originalPrice: 3499,
    reloopPrice: 3499,
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    category: "clothing",
    brand: "Levi's",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 10,
    co2SavedKg: 0.5,
    status: "active",
    views: 134,
    isReturnedItem: false,
  },
  {
    title: "Philips Air Fryer HD9252",
    description: "2.5L capacity, Rapid Air technology. Uses up to 90% less fat. 1400W. New in box.",
    originalPrice: 8499,
    reloopPrice: 8499,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop",
    category: "appliances",
    brand: "Philips",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 15,
    co2SavedKg: 1.0,
    status: "active",
    views: 255,
    isReturnedItem: false,
  },
  {
    title: "JBL Flip 6 Bluetooth Speaker",
    description: "Bold JBL Original Pro Sound, IP67 waterproof, 12h battery. New sealed box.",
    originalPrice: 11999,
    reloopPrice: 11999,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "JBL",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 15,
    co2SavedKg: 0.8,
    status: "active",
    views: 189,
    isReturnedItem: false,
  },
  {
    title: "Adidas Ultraboost 22",
    description: "Responsive BOOST cushioning, Primeknit+ upper, Continental™ rubber outsole.",
    originalPrice: 16999,
    reloopPrice: 16999,
    imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=400&fit=crop",
    category: "footwear",
    brand: "Adidas",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 18,
    co2SavedKg: 1.0,
    status: "active",
    views: 176,
    isReturnedItem: false,
  },
  {
    title: "Kindle Paperwhite (11th Gen)",
    description: "6.8-inch 300 ppi display, adjustable warm light, 20-week battery, IPX8 waterproof.",
    originalPrice: 14999,
    reloopPrice: 14999,
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Amazon",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 18,
    co2SavedKg: 0.9,
    status: "active",
    views: 210,
    isReturnedItem: false,
  },
  {
    title: "Canon EOS M50 Mark II Camera",
    description: "24.1MP APS-C CMOS sensor, 4K video, built-in Wi-Fi & Bluetooth. Kit with 15-45mm lens.",
    originalPrice: 65000,
    reloopPrice: 65000,
    imageUrl: "https://images.unsplash.com/photo-1606986628249-c06bef3617e8?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Canon",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 100,
    listingType: "certified",
    sellerName: "ReLoop Store",
    isCertified: true,
    greenCreditsEarned: 30,
    co2SavedKg: 3.0,
    status: "active",
    views: 287,
    isReturnedItem: false,
  },
];

// Returned product replicas — NOT shown in main feed; surfaced only on product detail pages
const returnedReplicas = [
  {
    title: "Apple AirPods Pro (2nd Gen)",
    description: "Returned after 2 weeks — original owner switched to over-ear. Works perfectly, all accessories included. AI-graded Excellent condition.",
    originalPrice: 24900,
    reloopPrice: 16800,
    imageUrl: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Apple",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 95,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 60,
    co2SavedKg: 3.2,
    status: "active",
    views: 142,
    isReturnedItem: true,
  },
  {
    title: "Sony WH-1000XM5 Headphones",
    description: "Minor scratches on headband, excellent audio performance. Refurbished by Sony-certified technicians. Tested and verified.",
    originalPrice: 29990,
    reloopPrice: 18500,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Sony",
    disposition: "refurbish",
    qualityGrade: "good",
    qualityScore: 82,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 45,
    co2SavedKg: 4.1,
    status: "active",
    views: 98,
    isReturnedItem: true,
  },
  {
    title: "Nike Air Max 270 — Size 10",
    description: "Returned due to size mismatch. Worn once indoors. No visible wear. AI-graded Excellent.",
    originalPrice: 10995,
    reloopPrice: 7200,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    category: "footwear",
    brand: "Nike",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 93,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 55,
    co2SavedKg: 1.8,
    status: "active",
    views: 67,
    isReturnedItem: true,
  },
  {
    title: "Samsung Galaxy Tab S9",
    description: "Returned for size preference. Screen pristine, full kit included. AI inspection: 96/100.",
    originalPrice: 72999,
    reloopPrice: 52000,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4cec9d125?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Samsung",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 96,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 80,
    co2SavedKg: 5.6,
    status: "active",
    views: 213,
    isReturnedItem: true,
  },
  {
    title: "Levi's 512 Slim Taper Jeans — 32x32",
    description: "Gifted but wrong size. Tags still on, never worn. Perfect condition.",
    originalPrice: 3499,
    reloopPrice: 1999,
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    category: "clothing",
    brand: "Levi's",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 99,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 35,
    co2SavedKg: 0.9,
    status: "active",
    views: 34,
    isReturnedItem: true,
  },
  {
    title: "Philips Air Fryer HD9252",
    description: "Used 3 times, fully functional. Returned — customer upgraded to larger model. Deep cleaned and certified.",
    originalPrice: 8499,
    reloopPrice: 5500,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop",
    category: "appliances",
    brand: "Philips",
    disposition: "refurbish",
    qualityGrade: "good",
    qualityScore: 78,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 40,
    co2SavedKg: 2.1,
    status: "active",
    views: 55,
    isReturnedItem: true,
  },
  {
    title: "JBL Flip 6 Bluetooth Speaker",
    description: "Returned — purchased duplicate. Sealed in original packaging. Never opened.",
    originalPrice: 11999,
    reloopPrice: 8400,
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "JBL",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 98,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 50,
    co2SavedKg: 1.5,
    status: "active",
    views: 89,
    isReturnedItem: true,
  },
  {
    title: "Adidas Ultraboost 22 — Size 9",
    description: "Slight sole wear from 2 runs. Structurally perfect, cleaned and inspected. AI grade: Good.",
    originalPrice: 16999,
    reloopPrice: 10500,
    imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=400&fit=crop",
    category: "footwear",
    brand: "Adidas",
    disposition: "refurbish",
    qualityGrade: "good",
    qualityScore: 76,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 40,
    co2SavedKg: 2.0,
    status: "active",
    views: 76,
    isReturnedItem: true,
  },
  {
    title: "Kindle Paperwhite (11th Gen)",
    description: "Switching to physical books. Perfect working condition, includes original leather case.",
    originalPrice: 14999,
    reloopPrice: 9500,
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Amazon",
    disposition: "resell",
    qualityGrade: "excellent",
    qualityScore: 94,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 55,
    co2SavedKg: 1.9,
    status: "active",
    views: 110,
    isReturnedItem: true,
  },
  {
    title: "Canon EOS M50 Mark II Camera",
    description: "Used for 6 months, barely used. Includes 2 lenses, bag, and all accessories. AI-graded Good.",
    originalPrice: 65000,
    reloopPrice: 42000,
    imageUrl: "https://images.unsplash.com/photo-1606986628249-c06bef3617e8?w=400&h=400&fit=crop",
    category: "electronics",
    brand: "Canon",
    disposition: "resell",
    qualityGrade: "good",
    qualityScore: 88,
    listingType: "certified",
    sellerName: "ReLoop Certified",
    isCertified: true,
    greenCreditsEarned: 70,
    co2SavedKg: 6.2,
    status: "active",
    views: 187,
    isReturnedItem: true,
  },
];

const sampleP2PListings = [
  {
    sellerId: "system",
    sellerName: "Meera K.",
    title: "IKEA Standing Desk — 140x60cm",
    description: "Relocating city. 1 year old, no scratches, includes cable management tray.",
    price: 12000,
    originalPrice: 22000,
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop",
    category: "furniture",
    qualityGrade: "good",
    condition: "Good",
    location: "Bangalore, IN",
    status: "active",
    views: 65,
  },
  {
    sellerId: "system",
    sellerName: "Rohit A.",
    title: "Bosch Drill Machine Set",
    description: "Complete drill set with all attachments. Used twice. Moving abroad.",
    price: 3500,
    originalPrice: 6500,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop",
    category: "tools",
    qualityGrade: "excellent",
    condition: "Like New",
    location: "Delhi, IN",
    status: "active",
    views: 43,
  },
  {
    sellerId: "system",
    sellerName: "Priya S.",
    title: "Dyson V11 Cordless Vacuum",
    description: "Upgrading to newer model. Works perfectly, all heads included.",
    price: 22000,
    originalPrice: 42000,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    category: "appliances",
    qualityGrade: "good",
    condition: "Good",
    location: "Mumbai, IN",
    status: "active",
    views: 91,
  },
];

export const seed = new Hono()
  .post("/", async (c) => {
    // Seed marketplace products
    const existingProducts = await db.select().from(schema.products);
    if (existingProducts.length === 0) {
      await db.insert(schema.products).values([...originalProducts, ...returnedReplicas] as any);
    }

    // Seed p2p listings
    const existingListings = await db.select().from(schema.p2pListings);
    if (existingListings.length === 0) {
      await db.insert(schema.p2pListings).values(sampleP2PListings as any);
    }

    return c.json({ success: true, message: "Marketplace data seeded" }, 200);
  });
